// Generated by `npm run generate`. Do not edit.
// Source of truth is guesstimate/api/schemas.py.

export interface paths {
    "/game": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * New Game
         * @description Start a game.
         */
        post: operations["new_game_game_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/game/{game_id}/state": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get State
         * @description The board so far.
         */
        get: operations["get_state_game__game_id__state_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/game/{game_id}/candidates": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Candidates
         * @description Surviving candidates as grid positions.
         */
        get: operations["get_candidates_game__game_id__candidates_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/game/{game_id}/guess": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Post Guess
         * @description Play a code. Only modes that can score one accept this.
         */
        post: operations["post_guess_game__game_id__guess_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/game/{game_id}/solver-guess": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Get Solver Guess
         * @description The solver's opening move.
         *
         *     Only needed once per game. Every later move arrives with the answer to
         *     the previous one, since watch mode strictly alternates and a separate
         *     round trip per turn would buy nothing.
         */
        get: operations["get_solver_guess_game__game_id__solver_guess_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/game/{game_id}/solver-turn": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Post Solver Turn
         * @description Let the solver take its turn against the same secret.
         *
         *     Race only. The solver's board is kept separate from the player's, so
         *     this does not touch `state.turns` -- the two are racing, not sharing a
         *     sequence of moves.
         */
        post: operations["post_solver_turn_game__game_id__solver_turn_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/game/{game_id}/feedback": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Post Feedback
         * @description Answer the solver, and get its next move back.
         */
        post: operations["post_feedback_game__game_id__feedback_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /**
         * CandidatesResponse
         * @description Surviving candidates, as positions in `all_candidates(ruleset)`.
         *
         *     Indices, not codes: the ordering is the grid ordering in DESIGN.md, so the
         *     visualisation consumes these directly instead of rebuilding a
         *     code-to-position table the server already has.
         */
        CandidatesResponse: {
            /** Total */
            total: number;
            /** Indices */
            indices: number[];
        };
        /**
         * ErrorResponse
         * @description A refusal, with a machine-readable reason.
         */
        ErrorResponse: {
            /**
             * Error
             * @enum {string}
             */
            error: "inconsistent_feedback" | "game_over" | "wrong_mode" | "not_found" | "invalid" | "rate_limited";
            /** Detail */
            detail: string;
        };
        /**
         * FeedbackRequest
         * @description An answer to the solver's last guess, as `+B-C`.
         */
        FeedbackRequest: {
            /** Feedback */
            feedback: string;
        };
        /**
         * GameStateSchema
         * @description Everything a client may know right now.
         */
        GameStateSchema: {
            /** Id */
            id: string;
            /** Mode */
            mode: string;
            ruleset: components["schemas"]["RulesetSchema"];
            /** Turns */
            turns: components["schemas"]["TurnSchema"][];
            /** Finished */
            finished: boolean;
            /** Won */
            won: boolean;
            secret: components["schemas"]["SecretSchema"];
            /** Surviving */
            surviving: number;
            /**
             * Space Size
             * @description How many codes the ruleset allows in total. Served rather than left for the client to derive: it is a falling factorial or a power depending on `allow_repeats`, and a second implementation of that in another language is a divergence waiting to happen somewhere no Python test can reach.
             */
            space_size: number;
            /**
             * Outcomes
             * @description Every answer this ruleset can actually produce, as `+B-C`. Sent because it is not derivable from the code length: which outcomes are reachable depends on the alphabet too. Four positions over two symbols with repeats reaches nine of the fourteen a bulls-plus-cows triangle would suggest, so a client computing the set itself would offer answers that can never be correct.
             */
            outcomes: string[];
        };
        /**
         * GuessRequest
         * @description A code to play.
         */
        GuessRequest: {
            /** Guess */
            guess: string;
        };
        /**
         * NewGameRequest
         * @description What to start.
         */
        NewGameRequest: {
            /**
             * Mode
             * @default codebreaker
             * @enum {string}
             */
            mode: "codebreaker" | "watch" | "race" | "evil";
            ruleset?: components["schemas"]["RulesetSchema"];
            /**
             * Solver
             * @default entropy
             */
            solver: string;
            /** Seed */
            seed?: number | null;
            /**
             * Secret
             * @description Fix the code, for demos and reproducible tests. Ignored by watch mode, which has no secret.
             */
            secret?: string | null;
        };
        /**
         * RaceTurnSchema
         * @description One turn by the solver in a race, scored against the shared secret.
         */
        RaceTurnSchema: {
            /** Guess */
            guess: string;
            /** Feedback */
            feedback: string;
            /** Finished */
            finished: boolean;
            /** Surviving */
            surviving: number;
        };
        /**
         * RulesetSchema
         * @description The rules a game is played under.
         */
        RulesetSchema: {
            /**
             * Length
             * @default 4
             */
            length: number;
            /**
             * Alphabet
             * @default 123456789
             */
            alphabet: string;
            /**
             * Allow Repeats
             * @default false
             */
            allow_repeats: boolean;
        };
        /**
         * SecretSchema
         * @description Three states, discriminated on the wire as they are in the domain.
         *
         *     `kind` is always present, so a client can tell a withheld secret from one
         *     that never existed without inspecting whether `code` happens to be null.
         */
        SecretSchema: {
            /**
             * Kind
             * @enum {string}
             */
            kind: "hidden" | "revealed" | "never";
            /** Code */
            code?: string | null;
        };
        /**
         * SolverTurnResultSchema
         * @description A turn in a mode where the solver moves next.
         *
         *     `next_guess` is null exactly when `finished` is true, matching the domain
         *     invariant, so watch mode needs one round trip per turn rather than two.
         */
        SolverTurnResultSchema: {
            /** Feedback */
            feedback: string;
            /** Finished */
            finished: boolean;
            /** Surviving */
            surviving: number;
            /** Next Guess */
            next_guess?: string | null;
        };
        /**
         * TurnResultSchema
         * @description What one turn produced.
         */
        TurnResultSchema: {
            /** Feedback */
            feedback: string;
            /** Finished */
            finished: boolean;
            /** Surviving */
            surviving: number;
        };
        /**
         * TurnSchema
         * @description One completed exchange.
         */
        TurnSchema: {
            /** Guess */
            guess: string;
            /** Feedback */
            feedback: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    new_game_game_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["NewGameRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GameStateSchema"];
                };
            };
            /** @description Refused before starting */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Rate limited */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_state_game__game_id__state_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                game_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["GameStateSchema"];
                };
            };
            /** @description No such game */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Wrong mode, or already over */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Malformed input */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Rate limited */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_candidates_game__game_id__candidates_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                game_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CandidatesResponse"];
                };
            };
            /** @description No such game */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Wrong mode, or already over */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Malformed input */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Rate limited */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    post_guess_game__game_id__guess_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                game_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["GuessRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TurnResultSchema"];
                };
            };
            /** @description No such game */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Wrong mode, or already over */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Malformed input */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Rate limited */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    get_solver_guess_game__game_id__solver_guess_get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                game_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: string;
                    };
                };
            };
            /** @description No such game */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Wrong mode, or already over */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Malformed input */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Rate limited */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    post_solver_turn_game__game_id__solver_turn_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                game_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RaceTurnSchema"];
                };
            };
            /** @description No such game */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Wrong mode, or already over */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Malformed input */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Rate limited */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    post_feedback_game__game_id__feedback_post: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                game_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["FeedbackRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SolverTurnResultSchema"];
                };
            };
            /** @description No such game */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Wrong mode, or already over */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Malformed input */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Rate limited */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
}
