/**
 * Regenerate `src/api/types.ts` from the running server's OpenAPI schema.
 *
 * The error codes are the reason this is generated rather than written. The
 * Python client keeps a table mapping each code to one exception; a copy of
 * that table in TypeScript would be the bug `docs/notes/protocol-is-not-a-
 * contract.md` is about, with a comment attached instead of a fix. Generated,
 * a code added on the server changes the union here, and any exhaustive switch
 * over it stops compiling -- a build failure rather than a runtime surprise in
 * someone's browser.
 */
import { execFileSync } from "node:child_process";
import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, resolve } from "node:path";
import openapiTS, { astToString } from "openapi-typescript";

const here = dirname(new URL(import.meta.url).pathname);
const repo = resolve(here, "..", "..");
const out = resolve(here, "..", "src", "api", "types.ts");

const schema = execFileSync(
  "uv",
  ["run", "python", "-c", "import json;from guesstimate.api import app;print(json.dumps(app.openapi()))"],
  { cwd: repo, encoding: "utf8", maxBuffer: 32 * 1024 * 1024 },
);

const ast = await openapiTS(JSON.parse(schema));
mkdirSync(dirname(out), { recursive: true });
writeFileSync(
  out,
  "// Generated by `npm run generate`. Do not edit.\n" +
    "// Source of truth is guesstimate/api/schemas.py.\n\n" +
    astToString(ast),
);
console.log(`wrote ${out}`);
